# Основные настройки плагина.
main_settings:
  # Отправлять статистику об использовании? (анонимно)
  # Оставляя true, вы мотивируете
  metrics: true
  # Форматирование сообщений.
  # legacy - &цвет.
  # minimessage - <цвет>.
  # Подробнее о MiniMessage: https://docs.papermc.io/adventure/minimessage/format/
  colorizer: minimessage
  # Файлы, с которых регистрируются слушатели.
  # Должны храниться в папке плагина. Можете добавлять свои.
  listeners_files:
    - 'blocks/blocks.yml'
    - 'blocks/ores.yml'
    - 'blocks/other.yml'
  # Файлы, в которых можно создавать предметы.
  # Должны храниться в папке плагина. Можете добавлять свои.
  items_files:
    - 'items/items.yml'
  # Файлы, в которых можно создавать группы параметров дропа.
  # Должны храниться в папке плагина. Можете добавлять свои.
  drop_params_files:
    - 'params/params.yml'
  # Настройки полномочий.
  permissions:
    # Перезагрузка плагина.
    reload: 'gembreak.reload'
# Сообщения плагина.
messages:
  # Префикс (заменяется от %prefix%)
  prefix: "<gradient:#FF6021:#FFA821>[GemBreak]</gradient><reset>"

  reloaded: "%prefix% <green>Конфигурации успешно перезагружены!"
  no_perms: "%prefix% <red>У Вас нет полномочий, чтобы использовать данное действие."
